### ISSUE TITLE
Poročilo, Binder

### ISSUE THREAD

**Issue by MarvinHerzog** [JanKolenc/APPR-2018-19#2]
Pozdravljen, pri študentih preverjam kakšno je stanje poročil za četrtkove predstavitve. Vidim, da še nisi spreminjal datoteke *projekt.Rmd*. Če želiš predstaviti svoj projekt v četrtek, svetujem, da pripraviš rmarkdown poročilo. Ko boš imel poročilo pripravljeno (ali v primeru, da boš imel težave) in se bo to uspešno prevedlo na Binderju [![Shiny](http://mybinder.org/badge.svg)](http://beta.mybinder.org/v2/gh/JanKolenc/APPR-2018-19/master?urlpath=shiny/APPR-2018-19/projekt.Rmd), komentiraj na tale issue, da dodamo tvoj projekt na [repozitorij za zagovore](https://github.com/jaanos/APPR-zagovori).

**Comment by JanKolenc** [comment]
Pozdravljeni, imel sem težave z osebnim računalnikom že od božiča ampak sem ga sedaj popravil in spet dela danes bom projekt probal še čimbolj dodelati na koncu pa pripravil pred jutrišnjim dnem vse za binder in predstavitev.

**Comment by MarvinHerzog** [comment]
Kar v miru, pripravi kar lahko. Če boš imel težave, pa komentiraj tukaj, da skupaj pogledamo.

**Comment by JanKolenc** [comment]
Uspelo mi je narediti tidy tabele in jih razporediti vse po letih.  Za predstavitev mislim, da nimam kaj dosti prikazati kar imam so le surovi podatki. Uredil sem projekt.Rmd ampak mi binder še ne dela(za kar bi rabim malo pomoči 😄 ). Naslednje stopnje projekta bom naredil na prihajajočih vajah in prihodnji vikend ko odpišemo Analizo 3 in Verjetnost teorijo. Glede težav z računalnikom sem že pisal asistentu Vidaliju jutri pa se bom pri predstavitvah pomenil še s profesorjem glede deadlinov.

**Comment by jaanos** [comment]
Poročila ti ne prevede, ker datoteke v mapi `podatki` navajaš samo z imeni. Prvo razpredelnico lahko npr. uvoziš tako:
```R
sl <- locale("sl", encoding = "Windows-1250", decimal_mark=".")
izobrazba <- read_delim("podatki/izobrazba.csv", ";", na="-", locale=sl,
                        col_names=c("1", "Starost", "Izobrazba", "Spol", 2008:2017)) %>%
  select(-1) %>% melt(id.vars=1:3, variable.name="Leto",
                      value.name="Odstotki", na.rm=TRUE) %>%
  mutate(Leto=parse_number(Leto))
```
Nobene potrebe ni, da razpredelnico razbijaš na manjše - če boš potreboval samo podmnožico podatkov (npr. za izris grafa), jo pridobiš, ko jo potrebuješ.

Seveda poskrbi, da imaš v RStudiu odprt projekt - če desno zgoraj piše *Project: (None)*, klikni tja, izberi *Open Project...*, nato pa poišči datoteko `APPR-2018-19.Rproj` v mapi svojega repozitorija (tako bo deloval tudi git znotraj RStudia).

Sicer pa, če zaenkrat še nimaš ničesar drugega, lahko v poročilu prikažeš kakšno razpredelnico (pomagaj si s funkcijo `head`, da pridobiš samo prvih nekaj vrstic, in `kable`, ki poskrbi za lep izpis). Sicer pa lahko tudi poskusiš izrisati kak graf iz uvoženih podatkov.

**Comment by jaanos** [comment]
Še to: glede na to, da zaenkrat nimaš Shiny aplikacije, iz glave poročila odstrani vrstico `runtime: shiny`.

**Comment by JanKolenc** [comment]
Pozdravljeni, nisem čisto razumel kaj moram popraviti sem poskušal pa ni bilo uspeha, pa bi prosil če se lahko oglasim pri vas po prvih dveh urah predstavitev oz ce bo mozno ze vmes, da skupaj pogledava kaj sem zamočil. 
Hvala

**Comment by jaanos** [comment]
Zgornji komentar se nanaša na `uvoz.r` - tja torej postaviš zgornjo kodo, in podobno poskrbiš tudi za ustrezen uvoz ostalih razpredelnic. Lahko torej sam poskusiš - za začetek naj se poročilo prevede pri tebi; ko to deluje, preizkusi še na Binderju. Če ne bo uspelo, se seveda lahko oglasiš po vajah.
